# Generated by Django 4.1.4 on 2023-01-02 06:33

import imagekit.models.fields
from django.db import migrations, models

import imagekitio_storage.storage
import imagekitio_storage.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestFileAndImageFieldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, storage=imagekitio_storage.storage.RawMediaImagekitStorage(),
                                          upload_to='raw-file-tests/')),
                ('image', models.ImageField(blank=True, storage=imagekitio_storage.storage.MediaImagekitStorage(),
                                            upload_to='image-file-tests/')),
            ],
        ),
        migrations.CreateModel(
            name='TestFileFieldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', models.FileField(blank=True, storage=imagekitio_storage.storage.RawMediaImagekitStorage(),
                                          upload_to='raw-file-tests/')),
            ],
        ),
        migrations.CreateModel(
            name='TestFileFieldVideoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('video', models.FileField(blank=True, storage=imagekitio_storage.storage.VideoMediaImagekitStorage(),
                                           upload_to='video-file-tests/',
                                           validators=[imagekitio_storage.validators.validate_video])),
            ],
        ),
        migrations.CreateModel(
            name='TestThirdPartyFieldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('file', imagekit.models.fields.ProcessedImageField(blank=True, height_field='height',
                                                                    storage=imagekitio_storage.storage.RawMediaImagekitStorage(),
                                                                    upload_to='third-party-raw-file-tests/',
                                                                    width_field='width')),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, height_field='height',
                                                                     storage=imagekitio_storage.storage.MediaImagekitStorage(),
                                                                     upload_to='third-party-image-tests/',
                                                                     width_field='width')),
                ('width', models.IntegerField(default=0, null=True)),
                ('height', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestWithoutMediaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
